baseURL = "https://basilcrow.com/"
languageCode = "en"

title = "Basil Crow"
theme = "antora-default-ui-hugo-theme"

copyright = "Copyright &copy; 2020 Basil Crow. All rights reserved."
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "UA-49851788-2"
ignoreFiles = [ "_includes" ]

[params]
  editThisPage = "https://github.com/basil/basilcrow.com/edit/master/content/"

[markup]
  [markup.asciidocext]
    trace = true
    verbose = true
    workingFolderCurrent = true
    [markup.asciidocext.attributes]
      "icons" = "font"
      "imagesdir" = "_images"
      "includedir" = "_includes"
      "source-highlighter" = "highlightjs"
  [markup.highlight]
    # Disable Goldmark Chroma syntax highlighter
    codeFences = false

[minify]
  disableCSS = true
  disableJS = true
  disableJSON = true
  disableSVG = true
  disableXML = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepQuotes = true
      keepWhitespace = true

[author]
  name = "Basil Crow"
  email = "me@basilcrow.com"
  github = "basil"
  twitter = "bcrow"
