baseURL = "http://basilcrow.com/"
languageCode = "en"

title = "Basil Crow"
theme = "antora-default-ui-hugo-theme"

copyright = "Copyright &copy; 2020 Basil Crow. All rights reserved."
googleAnalytics = "UA-49851788-2"
enableEmoji = true
enableRobotsTXT = true
ignoreFiles = [ "_includes" ]

[params]
  editThisPage = "https://github.com/basil/basilcrow.com/edit/master/content/"

[markup.asciidocext]
  trace = true
  verbose = true
  workingFolderCurrent = true

  [markup.asciidocext.attributes]
    "icons" = "font"
    "imagesdir" = "_images"
    "includedir" = "_includes"
    "source-highlighter" = "highlightjs"

[Author]
  name = "Basil Crow"
  email = "me@basilcrow.com"
  github = "basil"
  twitter = "bcrow"
