name: Build and deploy site

on:
  push:
    branches:
      - $default-branch
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/checkout@v2
        with:
          repository: basil/antora-default-ui-hugo-theme
          path: themes/antora-default-ui-hugo-theme

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - run: gem install asciidoctor

      - run: hugo -d public --gc --minify

      - uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          DEPLOY_KEY_FILE=$(mktemp -p ~/.ssh) || exit 1
          echo "${DEPLOY_KEY}" >"${DEPLOY_KEY_FILE}"
          chmod 0600 "${DEPLOY_KEY_FILE}"
          rsync -avzr --delete -e "ssh -i ${DEPLOY_KEY_FILE} -o LogLevel=quiet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" public/ ${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/basilcrow.com/
        shell: bash
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
